### ISSUE TITLE
Document extra string escape sequences supported by MMAR

### ISSUE THREAD

**Issue by Francessco121** [Francessco121/hlml-toolkit#12]
Current extras are:
- `\0` for ASCII null (`0x0000`).

**Comment by kevinramharak** [comment]
So these escape sequences are outside of string literals?

**Comment by Francessco121** [comment]
@KevinRamharak I'm not sure I understand your question. This issue is just for string escape sequences that MMAR supports that normal MAR doesn't (e.g. the `\0` example is could be used like `"Hello World\0"` to null terminate it).

**Comment by kevinramharak** [comment]
Yeah that was unclear from the title and the example snippets. So this is about the escape sequences inside a string literal. I wanted to clarify this since I was wondering why you would want escape sequences outside string literals

**Comment by Francessco121** [comment]
Ah, gotcha. I'll clarify the title.
