### ISSUE TITLE
String literal encoding

### ISSUE THREAD

**Issue by kevinramharak** [Francessco121/hlml-toolkit#14]
So i was wondering how you are planning to implement string literals and their encoding.

**Comment by Francessco121** [comment]
Likewise with my answer to #13, it's going to be the same way that the game's assembler does it. Each character will translate to a single UTF-16 character code and essentially just form an array of words. MMAR strings won't automatically be null terminated (as that would be a breaking change from MAR), but HLML strings will (and maybe a way to tell the compiler not to).

**Comment by Francessco121** [comment]
So, to fully answer this (now that I've confirmed it): MAR treats each string character as a UTF-16 value and encodes them, just like integers, in big-endian. The MMAR assembler does the same :).
