### ISSUE TITLE
Assembler needs to support unicode escape sequences in strings

### ISSUE THREAD

**Issue by Francessco121** [Francessco121/hlml-toolkit#9]
MAR supports the following escape sequence in strings: `\uXXXX` where each X is a hexadecimal digit. This turns into a single hexadecimal number (e.g. `\u1234` encodes `0x1234` at that position in the string).

**Comment by kevinramharak** [comment]
Do you plan to support more escape sequences. the C escape sequences?
 for example: https://en.wikipedia.org/wiki/Escape_sequences_in_C

**Comment by Francessco121** [comment]
@KevinRamharak Yep! I'm just starting off with the ones MAR supports (and `\0`) for now.

**Comment by kevinramharak** [comment]
Great. Ive started a while back on a C compiler for MAR, but never really got anywhere. Im still very interested in learning about compilers and how they work.

Ill be keeping an eye on this project. Starting off with a superset on assembly before doing the high level compiler is a smart way to start it off.

**Comment by Francessco121** [comment]
@KevinRamharak If you haven't already, I highly recommend the book [Crafting Interpreters by Bob Nystrom](https://craftinginterpreters.com/). It's where I learned a significant amount of my knowledge about this stuff, very well written, and free!

**Comment by kevinramharak** [comment]
Tnx, ive seen it and skimmed trough it before. I will definitely check it out once i have some more time on my hands.

**Comment by Francessco121** [comment]
Closed with c3a8abb4751b97d2fbec9ad7b2d8fd99f5bc3f62.
